"""PostGres

Revision ID: 443e7e1e5378
Revises: bb5c67771392
Create Date: 2021-09-12 02:16:46.322433

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "443e7e1e5378"
down_revision = "bb5c67771392"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
