"""Unit_indexing

Revision ID: 9a29f0bea2eb
Revises: 9177008d91d8
Create Date: 2021-09-22 14:58:42.545982

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9a29f0bea2eb"
down_revision = "9177008d91d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_units_slug"), "units", ["slug"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_units_slug"), table_name="units")
    # ### end Alembic commands ###
