"""PostGres

Revision ID: bb5c67771392
Revises: c26999586cb0
Create Date: 2021-09-12 02:14:15.272995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bb5c67771392"
down_revision = "c26999586cb0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
