"""Correction_price

Revision ID: cb72ae5e2b8d
Revises: 14dc5397a390
Create Date: 2021-09-19 14:44:29.188541

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "cb72ae5e2b8d"
down_revision = "14dc5397a390"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prices", sa.Column("price", sa.Numeric(), nullable=False))
    op.drop_column("prices", "prices")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prices", sa.Column("prices", sa.NUMERIC(), nullable=False))
    op.drop_column("prices", "price")
    # ### end Alembic commands ###
