"""Add_Coluns_Service

Revision ID: e9a19ea6d917
Revises: 56f9b475c92a
Create Date: 2021-09-11 18:11:59.914494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e9a19ea6d917"
down_revision = "56f9b475c92a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "services", ["code"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "services", type_="unique")
    # ### end Alembic commands ###
